class Action {
  static LIST_TODOS = "LIST_TODOS";
  static DELETE_TODO = "DELETE_TODO";
  static UPDATE_TODO = "UPDATE_TODO";
  static CREATE_TODO = "CREATE_TODO";
  static TOGGLE_ADDING_TODO_MODAL = "TOGGLE_ADDING_TODO_MODAL";
  static TOGGLE_UPDATING_TODO_MODAL = "TOGGLE_UPDATING_TODO_MODAL";
  static RESPONSE_SHOW_LIST_OK = "RESPONSE_SHOW_LIST_OK";
  static REQUEST_SHOW_LIST = "REQUEST_SHOW_LIST";
}

export default Action;
